# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a96e889a386cd05700ff026a330462764690c57a404c324987055568e518743615d7b6cfee5358bfd6538b5f2ce224d49e16ad39ced1a41e73053f6e241d75
  google_geocoder_api: AIzaSyBl_CWl-eUV8lQRyrrFG4Yp2BdJFV64wmA
  metabase_site_url: https://beachlab.herokuapp.com
  metabase_secret_key: 5e28de7be1f1ed1566d009cc4962af3be9d9b97749c43b9e24666c397a005fd4

test:
  secret_key_base: 66562f97e8f1731670f95d5f52f68dee01e3890d2bdde1b94d312a61accca229fea443eb2a5ab5a937f5ecf70c09bc8ef16571f43ee1a56913eff5418a93f6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_geocoder_api: <%= ENV["GOOGLE_GEOCODER_API"] %>
  metabase_site_url: <%= ENV["METABASE_SITE_URL"] %>
  metabase_secret_key: <%= ENV["METABASE_SECRET_KEY"] %>
